version: '3'
services:

  # バックエンド
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: vue-go-spa-sample-server
    ports:
      - 8000:8000
    tty: true # コンテナの起動永続化
    volumes:
      - ./server:/go/src/github.com/yasu2122yasu/vue-go-spa-sample/server
      - .git:/go/src/github.com/yasu2122yasu/vue-go-spa-sample/.git
    depends_on:
      - 'db'
  # フロントエンド
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vue-go-spa-sample-client
    ports:
      - 8080:8080
    tty: true # コンテナの起動永続化
    volumes:
      - ./client:/usr/src/app/client
      - .git:/usr/src/app/.git
  # DB
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: vue-go-spa-sample-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./db/mysql-store:/var/lib/mysql
      - ./db/mysql-logs:/var/log/mysql